### ISSUE TITLE
`value` doesn't update x_f

### ISSUE THREAD

**Issue by mohamed82008** [JuliaNLSolvers/NLSolversBase.jl#44]
https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/3923f847b55fbff56d250f63aab754a2ed452486/src/interface.jl#L6
Unlike https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/3923f847b55fbff56d250f63aab754a2ed452486/src/interface.jl#L3, `value` doesn't update `x_f` which seems assumed as the function is checking if `x != obj.x_f` before evaluating the objective. This condition will never be true if x_f is not updated and only the function `value` is used in the algorithm, not `value!`.

**Comment by mohamed82008** [comment]
This seems intentional though, as `gradient` goes through a long way to make sure `obj` is not touched, which seems kind of weird, but maybe I will see why things were done like this when I read further.

**Comment by anriseth** [comment]
Methods without an exclamation mark should not change/mutate the inputs,
which is why it does not update x_f.

The check on x_f is just to prevent unnecessary recalculation of the
objective, which is only relevant in the case where the previous call to
value! (or value!!) was at the same x-value.

(Did that answer your question?)

**Comment by mohamed82008** [comment]
Yes it does, thanks for clarifying.
